openapi: 3.0.0
info:
  title: Crime API
  description: API for fetching crime data in various cities
  version: 1.0.0

servers:
  - url: http://localhost:3000

paths:
  /crimes:
    get:
      summary: Get all crimes in Sundbyberg
      responses:
        200:
          description: A list of crimes
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object

  /crimes/locations:
    get:
      summary: Get all crime headlines in Sundbyberg
      responses:
        200:
          description: A list of crime headlines in a location
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /crimes/search:
    get:
      summary: Search for crimes in a specific city
      parameters:
        - name: city
          in: query
          required: true
          schema:
            type: string
          description: The city to search for crimes
      responses:
        200:
          description: A list of crimes
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object

  /crimes/latest:
    get:
      summary: Get the latest crime event
      responses:
        200:
          description: The most recent crime event
          content:
            application/json:
              schema:
                type: object
